// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vbcltontvlbnaawiqegc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZiY2x0b250dmxibmFhd2lxZWdjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQ4MjQ2MzQsImV4cCI6MjA1MDQwMDYzNH0.cBuTAwNNB4xM-FjwmTCGK6gIP3i7kQPfLaiI49eNVm0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);